export * from "../templates/t-badge.std";
export * from "../templates/t-code.std";
export * from "../templates/t-crumbs.std";
export * from "../templates/t-heading.std";
export * from "../templates/t-icon.std";
export * from "../templates/t-link.std";
export * from "../templates/t-localised.std";
export * from "../templates/t-paragraph.std";
export * from "../templates/t-richtext.std";
